# To boot the app run the following:
# docker-compose run auto-gpt
# NOTE: Version 3.9 requires at least docker-compose version 1.29.0 !
version: "3.9"

services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
    profiles: ["exclude-from-up"]
